version: '3.7'

# docker-compose up -d --build && docker image prune -f

services:
  calendar:
    build:
      context: ../../
      dockerfile: deployments/stage/calendar/Dockerfile
    image: calendar:latest
    container_name: calendar
    ports:
      - "8087:8087"
    restart: always
    depends_on:
      - postgres
    networks:
      - stage_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otus
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    restart: always
    networks:
      - stage_network

networks:
  stage_network:
    driver: bridge

volumes:
  postgres: