gRPC_server:
  addr: "0.0.0.0:8090"

db:
  host: "localhost"
  port: 5450
  name: "otus"
  username: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_conn: 10

logger:
  file_name: "./calendar.log"
  max_size: 50
  level: "info"
